title: Chris Pedder's Blog
iconURL: assets/default-icon.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  github: ChrisPedder

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
google_analytics: UA-NNNNNNNN-N

# Build settings
markdown: kramdown
